Repository integr8ly/installation, pull requests merged in 2019-08, with the labels that each got.

#822 split mobile playbook to 2 parts and run them at different time
  playbooks/install.yml
  playbooks/install_mobile_manifest.yml
  playbooks/install_mobile_services.yml
Labels: mobile

#826 uninstall mobile services as part of the overall uninstall
  playbooks/uninstall.yml
Labels: mobile

#823 only set the url for the mobile walkthrough
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/templates/cr.yaml.j2
Labels: mobile

#833 fix(grafana) : Uptime App Server (AEROGEAR-9714)
  roles/mobile_security_service/templates/mss_grafana_dashboard.yml.j2
Labels: mobile

#834 feat(ups grafana dash) : Upgrade it with the latest version
  roles/ups/templates/grafana_dashboard.yml.j2
Labels: mobile

#835 Make UPS role wait for enmasse resources
  roles/ups/tasks/install-operator.yml
  roles/ups/tasks/install-server.yml
Labels: mobile

#837 disable mobile services by default for managed clusters
  inventories/managed.template
  playbooks/install_mobile_manifest.yml
  playbooks/install_mobile_services.yml
Labels: mobile

#843 Add mobile services
  inventories/group_vars/all/manifest.yaml
  inventories/managed.template
  library/manifest_add.py
  playbooks/generate-customisation-inventory.yml
  playbooks/install.yml
  playbooks/install_mobile_manifest.yml
  playbooks/install_mobile_services.yml
  playbooks/install_services.yml
  playbooks/install_user_rhsso.yml
  playbooks/uninstall.yml
  playbooks/uninstall_mobile.yml
  roles/customisation/tasks/main.yaml
  roles/customisation/templates/inventory.j2
  roles/datasync/defaults/main.yml
  roles/mdc/defaults/main.yml
  roles/mdc/templates/mdc_grafana_dashboard.yaml.j2
  roles/mdc/templates/mdc_prometheus_rules.yaml.j2
  roles/mdc/templates/operator_prometheus_rules.yaml.j2
  roles/middleware_monitoring_config/tasks/get_blackbox_routes.yml
  roles/middleware_monitoring_config/templates/blackboxtargets.yml.j2
  roles/mobile_security_service/tasks/backup.yml
  roles/mobile_security_service/templates/mss_grafana_dashboard.yml.j2
  roles/mobile_security_service/templates/mss_operator_prometheus_rule.yml.j2
  roles/mobile_security_service/templates/mss_prometheus_rule.yml.j2
  roles/rhsso/tasks/apply_ocp_roles.yaml
  roles/ups/defaults/main.yml
  roles/ups/tasks/backup.yml
  roles/ups/tasks/install-operator.yml
  roles/ups/tasks/install-server.yml
  roles/ups/templates/grafana_dashboard.yml.j2
  roles/ups/templates/operator_prometheus_rule.yml.j2
  roles/ups/templates/prometheus_rule.yml.j2
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/templates/cr.yaml.j2
Labels: mobile

#773 [WIP] amq-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/enmasse/defaults/main.yml
  roles/enmasse/templates/enmasse_hosts.j2
Labels: amq-online, product update

#855 fix: uninstall datasync
  playbooks/uninstall_mobile.yml
  roles/datasync/tasks/uninstall.yml
Labels: mobile

#702 [WIP] fuse-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/fuse/tasks/main.yml
  roles/fuse/tasks/upgrade.yml
  roles/fuse_managed/tasks/main.yml
  roles/fuse_managed/tasks/upgrade.yml
Labels: fuse-online, product update

#856 Webapp mdc
  inventories/group_vars/all/manifest.yaml
  playbooks/install_mobile_services.yml
  playbooks/install_services.yml
  roles/msbroker/tasks/apply_msbroker_template.yml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/templates/cr.yaml.j2
Labels: mobile

#867 fix(graphs) :Replace title Daily Percentage Uptime for Average Percentage Uptime
  roles/mdc/templates/operator_grafana.yaml.j2
  roles/ups/templates/operator_grafana_dashboard.yml.j2
Labels: mobile

#894 [WIP] 3scale update
  inventories/group_vars/all/manifest.yaml
  roles/3scale/defaults/main.yml
  roles/3scale/tasks/install.yml
  roles/customisation/tasks/main.yaml
  roles/middleware_monitoring_config/tasks/get_blackbox_routes.yml
  roles/msbroker/tasks/apply_msbroker_template.yml
Labels: 3Scale, integration tests, product update

#902 Adding SLIs for 3Scale
  roles/middleware_monitoring_config/defaults/main.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_3scale_alerts.yml.j2
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: Verified

#934 [WIP] middleware-monitoring update
  inventories/group_vars/all/manifest.yaml
Labels: middleware-monitoring, product update

#938 unique names for the sso backup role bindings
  roles/rhsso/tasks/backup.yaml
Labels: Verified
