Repository integr8ly/installation, pull requests merged in 2019-06, with the labels that each got.

#675 [WIP] webapp update
  inventories/group_vars/all/manifest.yaml
Labels: product update, webapp

#687 Mobile security service install/uninstall
  inventories/group_vars/all/common.yml
  inventories/group_vars/all/manifest.yaml
  playbooks/install_services.yml
  playbooks/uninstall.yml
  playbooks/upgrades/upgrade.yaml
  roles/customisation/tasks/main.yaml
  roles/customisation/templates/inventory.j2
  roles/mobile_security_service/defaults/main.yml
  roles/mobile_security_service/tasks/main.yml
  roles/mobile_security_service/tasks/uninstall_mss.yml
  roles/mobile_security_service/tasks/upgrade.yml
  roles/mobile_security_service/templates/operator.yml.j2
Labels: Verified

#718 [WIP] backup-container update
  inventories/group_vars/all/manifest.yaml
Labels: backup-container, product update

#538 codeready update 1.2.0
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/code-ready/tasks/download_installer.yml
  roles/code-ready/tasks/install.yml
  roles/code-ready/tasks/main.yaml
  roles/code-ready/tasks/upgrade_1.0_to_1.2.yml
Labels: codeready, product update

#706 adding mss monitoring resources
  inventories/group_vars/all/manifest.yaml
  roles/mobile_security_service/defaults/main.yml
Labels: Verified
