Repository integr8ly/installation, pull requests merged in 2019-11, with the labels that each got.

#1096 Explicitly remove the mdc oauthclient
  roles/mdc/tasks/uninstall.yml
Labels: approved, lgtm, size/XS

#1101 Environment inventories refactor cherry pick
  inventories/group_vars/all/common.yml
  inventories/group_vars/all/manifest.yaml
  inventories/group_vars/osd/osd.yml
  inventories/group_vars/pds/pds.yml
  inventories/group_vars/poc/poc.yml
  inventories/managed.template
  inventories/osd.template
  inventories/pds.template
  inventories/poc.template
  playbooks/install_services.yml
  roles/3scale/defaults/main.yml
  roles/backup/defaults/main.yml
  roles/imagestream_pull_secret/defaults/main.yml
  roles/launcher/defaults/main.yml
  roles/openshift/defaults/main.yml
  roles/prerequisites/defaults/main.yml
  roles/rhsso/defaults/main.yml
Labels: approved, lgtm, size/L

#1105 fix grafana clusterroles on upgrade and make prometheus upgrade less …
  roles/middleware_monitoring/tasks/upgrade/grafana.yml
  roles/middleware_monitoring/tasks/upgrade/prometheus.yml
Labels: approved, lgtm, size/M

#1098 add SOP link to alerts
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm, size/XS

#1106 Adding image upgrade logic to 3Scale role
  roles/3scale/defaults/main.yml
  roles/3scale/tasks/upgrade_images.yml
Labels: approved, lgtm, size/S

#1116 treat master url string as undefined if empty
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
Labels: approved, lgtm, size/XS

#1117 Cherry pick 60a0f23 c216c78
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
Labels: approved, lgtm, size/XS

#1115 remove hardcoded namespace
  roles/middleware_monitoring/tasks/upgrade/prometheus.yml
Labels: approved, lgtm, size/XS

#1118 Setting prometheus size to 50 GB for OSD
  inventories/group_vars/osd/osd.yml
Labels: approved, lgtm, size/XS

#1119 Setting prometheus vol size to 50 GB for OSD
  inventories/group_vars/osd/osd.yml
Labels: approved, lgtm, size/XS

#1091 DOCS for monitoring
  docs/monitoring_docs.adoc
Labels: approved, lgtm, size/L

#1121 INTLY-4060 - don't install backups to PoC by default
  inventories/group_vars/poc/poc.yml
Labels: approved, lgtm, size/XS

#1114 INTLY-4011 - AMQ patch upgrade task
  roles/enmasse/tasks/upgrade.yml
  roles/enmasse/tasks/upgrade_images.yml
Labels: INTLY-3659-patch-upgrades, approved, lgtm, size/M

#1104 INTLY-3980 - new codeready task for image upgrades
  playbooks/generate-customisation-inventory.yml
  playbooks/install_backups.yml
  playbooks/install_services.yml
  playbooks/uninstall.yml
  playbooks/update_resources.yml
  roles/code-ready/tasks/upgrade.yml
  roles/code-ready/tasks/upgrade_images.yml
  roles/codeready/defaults/main.yml
  roles/codeready/tasks/backup.yml
  roles/codeready/tasks/download_installer.yml
  roles/codeready/tasks/install.yml
  roles/codeready/tasks/keycloak-client.yml
  roles/codeready/tasks/main.yaml
  roles/codeready/tasks/new_limits.yml
  roles/codeready/tasks/uninstall.yml
  roles/codeready/tasks/upgrade_1.0_to_1.2.yml
  roles/codeready/tasks/upgrade_images.yml
  roles/codeready/templates/config.yaml
  roles/codeready/templates/keycloak/client.json
Labels: INTLY-3659-patch-upgrades, approved, lgtm, size/M

#1125 INTLY-4060 - don't install backups to PoC by default
  inventories/group_vars/poc/poc.yml
Labels: approved, lgtm, size/XS

#1131 Enabled DataSync by default on OSD
  inventories/group_vars/osd/osd.yml
Labels: approved, lgtm, size/XS

#1129 Adding Apicurito upgrade image logic
  roles/apicurito/defaults/main.yml
  roles/apicurito/tasks/upgrade_images.yml
Labels: approved, lgtm, size/S

#1130 Adding rhsso image upgrade logic
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/upgrade_images.yml
Labels: approved, lgtm, size/S

#1075 INTLY-3843 Fixing alert manager and prometheus service account roles
  inventories/group_vars/all/manifest.yaml
  roles/middleware_monitoring/templates/alert_manager_cluster_role_binding.yml.j2
  roles/middleware_monitoring/templates/application_monitoring_cr.yml.j2
  roles/middleware_monitoring/templates/prometheus_cluster_role_binding.yml.j2
Labels: approved, lgtm, size/S

#1077 ups-operator update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrades/upgrade.yaml
  roles/ups/defaults/main.yml
  roles/ups/tasks/upgrade_images.yml
Labels: approved, lgtm, product update, size/M, ups-operator

#1132 Intly 3965 modifcations
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm, size/S

#1142 Adding CVE rollout playbook
  playbooks/cve_rollout.yml
  playbooks/group_vars/all/cve.yml
Labels: approved, lgtm, size/S

#1133 bump fuse online and amq online versions
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/fuse/tasks/_upgrade_fuse_online_imagestreams.yml
  roles/middleware_monitoring/tasks/upgrade/grafana.yml
Labels: approved, lgtm, size/M

#1156 Adding keycloak operator patch task for CVE rollouts
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/upgrade.yaml
  roles/rhsso/tasks/upgrade_images.yml
Labels: approved, lgtm, size/XS

#1155 INTLY-4160 - extract postgresql image to a variable in Enmasse
  roles/enmasse/defaults/main.yml
  roles/enmasse/tasks/upgrade_images.yml
Labels: approved, lgtm, size/XS

#1154 INTLY-4012 Add Fuse managed upgrade task
  playbooks/group_vars/all/cve.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/upgrade_images.yml
Labels: approved, lgtm, size/M

#1157 🔀 Revert "Merge pull request #1077 from integr8ly/ups-operator-ga"
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrades/upgrade.yaml
  roles/ups/defaults/main.yml
  roles/ups/tasks/upgrade_images.yml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#1150 Intly 3920 and 4040 cherry pick
  roles/middleware_monitoring/tasks/upgrade/grafana.yml
  roles/middleware_monitoring/tasks/upgrade/prometheus.yml
  roles/middleware_monitoring/tasks/upgrade/trigger.yml
Labels: approved, lgtm, size/L

#1050 removed wt2 route creation
  roles/3scale/tasks/_wt2_route.yml
  roles/3scale/tasks/install.yml
  roles/3scale/tasks/routes.yml
Labels: approved, lgtm, size/M

#1108 amq-online update
  inventories/group_vars/all/manifest.yaml
Labels: amq-online, approved, lgtm, product update, size/XS

#1159 INTLY-4159 update codeready upgrade_images task
  roles/codeready/defaults/main.yml
  roles/codeready/tasks/upgrade_images.yml
Labels: approved, lgtm, size/M

#1162 🔥 Terminate MSS with extreme prejudice
  README.adoc
  inventories/group_vars/all/manifest.yaml
  inventories/group_vars/poc/poc.yml
  playbooks/generate-customisation-inventory.yml
  playbooks/install_backups.yml
  playbooks/install_middleware_monitoring_config.yml
  playbooks/install_mobile_services.yml
  playbooks/mobile_generate_manifest.yml
  playbooks/uninstall_mobile.yml
  playbooks/update_resources.yml
  playbooks/upgrade.yml
  playbooks/upgrades/upgrade.yaml
  roles/middleware_monitoring_config/tasks/get_blackbox_routes.yml
  roles/middleware_monitoring_config/templates/blackboxtargets.yml.j2
  roles/mobile_security_service/OWNERS
  roles/mobile_security_service/defaults/main.yml
  roles/mobile_security_service/tasks/backup.yml
  roles/mobile_security_service/tasks/main.yml
  roles/mobile_security_service/tasks/monitoring.yml
  roles/mobile_security_service/tasks/new_limits.yml
  roles/mobile_security_service/tasks/upgrade.yml
  roles/mobile_security_service/tasks/upgrade_images.yml
  roles/mobile_security_service/templates/backup_cr.yml.j2
  roles/mobile_security_service/templates/cluster_role_binding.yml.j2
  roles/mobile_security_service/templates/mss_grafana_dashboard.yml.j2
  roles/mobile_security_service/templates/mss_operator_grafana_dashboard.yml.j2
  roles/mobile_security_service/templates/mss_operator_prometheus_rule.yml.j2
  roles/mobile_security_service/templates/mss_prometheus_rule.yml.j2
  roles/mobile_security_service/templates/operator.yml.j2
Labels: approved, lgtm, size/XXL

#1123 INTLY-3211 Docs: Adding Custom monitoring rules and alerts
  docs/customisation.md
  docs/monitoring/customisation.md
  docs/monitoring/grafana-endpoints-detailed.png
  docs/monitoring/prometheus-alert-working.png
Labels: approved, lgtm, size/L

#1166 Intly 3670 create monitoring docs
  docs/monitoring_docs.asciidoc
Labels: size/XS

#1168 rm mss first, so monitoring is reloaded correctly
  playbooks/upgrades/upgrade.yaml
Labels: approved, lgtm, size/S

#1160 INTLY-3828: Add rhmi label to namespaces created by integreatly installation
  playbooks/upgrades/upgrade.yaml
  roles/namespace/defaults/main.yml
  roles/namespace/tasks/upgrade.yml
  roles/namespace/templates/namespace.yml.j2
Labels: approved, lgtm, size/S

#1164 Fuse 1.8 Install
  inventories/group_vars/all/manifest.yaml
  roles/fuse/tasks/main.yml
  roles/fuse/tasks/uninstall.yml
  roles/fuse/tasks/upgrade.yml
  roles/fuse_managed/tasks/main.yml
  roles/fuse_managed/tasks/uninstall.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/templates/syndesis-customresource.yml.j2
  roles/msbroker/defaults/main.yml
  roles/msbroker/tasks/apply_msbroker_template.yml
Labels: approved, lgtm, size/L

#1171 Remove MDC
  README.adoc
  inventories/group_vars/all/manifest.yaml
  inventories/group_vars/poc/poc.yml
  playbooks/apply_mdc_manifest.yml
  playbooks/generate-customisation-inventory.yml
  playbooks/install.yml
  playbooks/install_mdc.yml
  playbooks/install_middleware_monitoring_config.yml
  playbooks/install_mobile_manifest.yml
  playbooks/install_mobile_services.yml
  playbooks/mobile_generate_manifest.yml
  playbooks/mobile_restart_master.yml
  playbooks/uninstall_mobile.yml
  playbooks/update_resources.yml
  playbooks/upgrade.yml
  playbooks/upgrades/upgrade.yaml
  roles/customisation/tasks/main.yaml
  roles/mdc/OWNERS
  roles/mdc/defaults/main.yml
  roles/mdc/library/mdc_patch_manifest.py
  roles/mdc/tasks/cors.yml
  roles/mdc/tasks/install-console.yml
  roles/mdc/tasks/install-oauth-client.yml
  roles/mdc/tasks/install-operator.yml
  roles/mdc/tasks/main.yml
  roles/mdc/tasks/monitoring.yml
  roles/mdc/tasks/new_limits.yml
  roles/mdc/tasks/patch-manifest.yml
  roles/mdc/tasks/prereq.yml
  roles/mdc/tasks/uninstall.yml
  roles/mdc/tasks/upgrade_images.yml
  roles/mdc/templates/mdc_grafana_dashboard.yaml.j2
  roles/mdc/templates/mdc_prometheus_rules.yaml.j2
  roles/mdc/templates/mobiledeveloperconsole.yaml.j2
  roles/mdc/templates/oauth.yaml.j2
  roles/mdc/templates/operator.yaml.j2
  roles/mdc/templates/operator_grafana.yaml.j2
  roles/mdc/templates/operator_prometheus_rules.yaml.j2
  roles/mdc/test/install.yml
  roles/mdc/test/patch.yml
  roles/mdc/test/uninstall.yml
  roles/middleware_monitoring_config/tasks/get_blackbox_routes.yml
  roles/middleware_monitoring_config/templates/blackboxtargets.yml.j2
  roles/rhsso-user/defaults/main.yml
  roles/rhsso-user/tasks/main.yml
  roles/ups/defaults/main.yml
  roles/ups/templates/operator.yml.j2
  roles/webapp/tasks/provision-webapp.yml
  scripts/upgrade.template.yml
Labels: approved, lgtm, size/XXL

#1167 replace MDC with UPS
  inventories/group_vars/all/manifest.yaml
  roles/msbroker/tasks/apply_msbroker_template.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
Labels: approved, lgtm, size/M

#1174 Bump 3scale version & fuse version for solution pattern
  inventories/group_vars/all/manifest.yaml
  roles/launcher/defaults/main.yml
  roles/namespace/defaults/main.yml
Labels: approved, lgtm, size/XS

#1175 Remove MDC namespace on upgrade
  playbooks/upgrades/upgrade.yaml
  roles/mdc/tasks/uninstall.yml
Labels: approved, lgtm, size/L

#1176 make sure the urls are correctly sanitised and the right part is pick…
  playbooks/upgrades/upgrade.yaml
  roles/mdc/tasks/uninstall.yml
  roles/webapp/tasks/upgrade.yaml
Labels: approved, lgtm, size/S

#1177 use fuse 1.8 3scale integration options instead of 1.7 options
  inventories/group_vars/all/manifest.yaml
  playbooks/install_services.yml
  roles/fuse_managed/tasks/config_3scale.yml
  roles/fuse_managed/templates/syndesis-customresource.yml.j2
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/M
