Repository integr8ly/installation, pull requests merged in 2019-10, with the labels that each got.

#1058 Remove github CODEOWNERS
  .github/CODEOWNERS
Labels: approved, lgtm, size/XS

#1060 RANDOM UPDATE
  README.adoc
Labels: approved, lgtm, size/XS

#1062 RANDOM UPDATE 2
  docs/release.md
Labels: approved, lgtm, size/XS

#1009 Updates to upgrades playbooks
  playbooks/upgrades/install_user_rhsso.yml
  playbooks/upgrades/upgrade.yaml
Labels: approved, lgtm

#1065 Modified CronJobsFailed PromQL query
  roles/backup/templates/backup-monitoring-alerts.yml.j2
Labels: approved, lgtm, size/XS

#1073 upgrade monitoring operator to 0.0.27
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/middleware_monitoring/tasks/upgrade/grafana.yml
  roles/middleware_monitoring/tasks/upgrade/prometheus.yml
  roles/middleware_monitoring/tasks/upgrade/trigger.yml
Labels: approved, lgtm, size/L

#1076 upgrade keycloak-operator version
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/rhsso-user/tasks/upgrade.yaml
  roles/rhsso/tasks/upgrade.yaml
Labels: approved, lgtm, size/M

#1072 Modified CronJobsFailed PromQL query
  roles/backup/templates/backup-monitoring-alerts.yml.j2
Labels: approved, lgtm, size/XS

#1083 INTLY-3909 Apply latest monitoring alerts during upgrade
  playbooks/upgrades/upgrade.yaml
  roles/backup/tasks/monitoring.yml
Labels: approved, lgtm, size/XS

#1084 INTLY-3905 Use 1.9.4 tag of keycloak operator that has correct matchi…
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1085 INTLY-3905 Cherrypick of keycloak operator version
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1049 Intly 3625 generic resource overrides all ns
  playbooks/update_resources.yml
  roles/3scale/defaults/main.yml
  roles/3scale/tasks/new_limits.yml
  roles/apicurito/defaults/main.yml
  roles/apicurito/tasks/new_limits.yml
  roles/code-ready/defaults/main.yml
  roles/code-ready/tasks/new_limits.yml
  roles/enmasse/defaults/main.yml
  roles/enmasse/tasks/new_limits.yml
  roles/fuse/defaults/main.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/new_limits.yml
  roles/launcher/defaults/main.yml
  roles/launcher/tasks/new_limits.yml
  roles/mdc/defaults/main.yml
  roles/mdc/tasks/install-operator.yml
  roles/mdc/tasks/monitoring.yml
  roles/mdc/tasks/new_limits.yml
  roles/middleware_monitoring/defaults/main.yml
  roles/middleware_monitoring/tasks/new_limits.yml
  roles/middleware_monitoring/tasks/uninstall.yml
  roles/middleware_monitoring/tasks/upgrade/trigger.yml
  roles/mobile_security_service/defaults/main.yml
  roles/mobile_security_service/tasks/new_limits.yml
  roles/resource_limits/defaults/main.yml
  roles/resource_limits/tasks/main.yml
  roles/resource_limits/tasks/patch_resource.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso-user/tasks/new_limits.yml
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/new_limits.yml
  roles/ups/defaults/main.yml
  roles/ups/tasks/install-operator.yml
  roles/ups/tasks/monitoring.yml
  roles/ups/tasks/new_limits.yml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/new_limits.yml
Labels: approved, lgtm, size/L

#1095 Add back monitoring resources to install
  roles/middleware_monitoring/tasks/main.yml
Labels: approved, lgtm, size/XS

#1079 Update release script to reset upgrade playbook on final release
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/3scale/tasks/upgrade_images.yml
  roles/amq_streams/tasks/upgrade_images.yml
  roles/apicurito/tasks/upgrade_images.yml
  roles/backup/tasks/upgrade_images.yml
  roles/code-ready/tasks/upgrade_images.yml
  roles/enmasse/tasks/upgrade_images.yml
  roles/fuse/tasks/upgrade_images.yml
  roles/fuse_managed/tasks/upgrade_images.yml
  roles/gitea/tasks/upgrade_images.yml
  roles/launcher/tasks/upgrade_images.yml
  roles/mdc/tasks/upgrade_images.yml
  roles/middleware_monitoring/tasks/upgrade_images.yml
  roles/mobile_security_service/tasks/upgrade_images.yml
  roles/msbroker/tasks/upgrade_images.yml
  roles/rhsso/tasks/upgrade_images.yml
  roles/ups/tasks/upgrade_images.yml
  roles/webapp/tasks/upgrade_images.yml
  scripts/release.sh
  scripts/upgrade.template.yml
  scripts/upgrade_vars.template.yml
Labels: approved, lgtm, size/L
