Repository integr8ly/installation, pull requests merged in 2019-12, with the labels that each got.

#1178 Delete MSS/MDC CRDs and MDC ServiceInstances
  playbooks/upgrades/upgrade.yaml
  roles/mdc/tasks/uninstall.yml
  roles/mobile_security_service/tasks/uninstall_mss.yml
Labels: approved, lgtm, size/S

#1179 INTLY-4100 standardise on pds cluster type
  inventories/group_vars/all/manifest.yaml
  inventories/group_vars/pds/pds.yml
Labels: approved, lgtm, size/XS

#1180 INTLY-4100 cherry-pick a6e0e89
  inventories/group_vars/all/manifest.yaml
  inventories/group_vars/pds/pds.yml
Labels: approved, lgtm, size/XS

#1183 update data sync templates
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/datasync/defaults/main.yml
  roles/datasync/tasks/main.yml
Labels: approved, lgtm, size/S

#1161 INTLY 3781 Add heimdall
  README.adoc
  inventories/group_vars/all/manifest.yaml
  playbooks/install.yml
  playbooks/install_heimdall.yml
  playbooks/install_heimdall_crs.yml
  playbooks/uninstall.yml
  playbooks/upgrades/upgrade.yaml
  roles/3scale/defaults/main.yml
  roles/3scale/tasks/heimdall.yml
  roles/3scale/tasks/install.yml
  roles/apicurito/defaults/main.yml
  roles/apicurito/tasks/heimdall.yml
  roles/apicurito/tasks/main.yml
  roles/codeready/defaults/main.yml
  roles/codeready/tasks/heimdall.yml
  roles/codeready/tasks/install.yml
  roles/enmasse/defaults/main.yml
  roles/enmasse/tasks/heimdall.yml
  roles/enmasse/tasks/install.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/heimdall.yml
  roles/fuse_managed/tasks/main.yml
  roles/heimdall/defaults/main.yml
  roles/heimdall/tasks/create_imagemonitor_cr.yml
  roles/heimdall/tasks/main.yml
  roles/heimdall/tasks/uninstall.yml
  roles/heimdall/tasks/upgrade_images.yml
  roles/heimdall/templates/cluster_role_binding.yml.j2
  roles/heimdall/templates/heimdall-dockercfg.yml.j2
  roles/heimdall/templates/imagemonitor-cr.yml.j2
  roles/middleware_monitoring_config/defaults/main.yml
  roles/middleware_monitoring_config/tasks/create_grafanadashboards.yml
  roles/middleware_monitoring_config/templates/images_cves.yml.j2
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/heimdall.yml
  roles/rhsso/tasks/main.yml
Labels: approved, lgtm, size/XL

#1185 3scale upgrade 2.6 to 2.7
  playbooks/upgrades/3scale_upgrade_2.5_to_2.6.yml
  playbooks/upgrades/upgrade.yaml
  roles/3scale/tasks/upgrade_2.6_to_2.7.yml
Labels: approved, lgtm, size/XL

#1165 ups update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/install_middleware_monitoring_config.yml
  playbooks/upgrades/upgrade.yaml
  roles/ups/defaults/main.yml
  roles/ups/tasks/install-server.yml
  roles/ups/tasks/monitoring.yml
  roles/ups/tasks/operator_upgrade_0.2.0_0.4.0.yaml
  roles/ups/tasks/uninstall.yml
  roles/ups/templates/operator.yml.j2
  roles/ups/templates/role_binding.yml.j2
  roles/ups/test/install_monitoring.yml
Labels: approved, lgtm, product update, size/L, ups

#1190 Add sync wt
  inventories/group_vars/all/manifest.yaml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
Labels: approved, lgtm, size/S

#1193 Updating README with latest install steps for RHPDS
  README.adoc
Labels: approved, lgtm, size/L

#1184 INTLY-4312 ensure cluster type is set
  README.adoc
  inventories/hosts.template
  inventories/tower.template
  roles/prerequisites/tasks/check_cluster_type.yml
  roles/prerequisites/tasks/main.yml
  roles/prerequisites/tasks/upgrade.yml
Labels: approved, lgtm, size/M

#1189 INTLY-4358 Upgrade monitoring clusterrolebindings to have correct ser…
  roles/middleware_monitoring/tasks/upgrade/prometheus.yml
Labels: approved, lgtm, size/XS

#1192 set default cluster_type to pds
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1138 docs: change oc version support in README
  README.adoc
Labels: approved, lgtm, size/XS

#1120 [INTLY-4046]: add evals user realms to user facing sso
  playbooks/install_user_rhsso.yml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/rhsso-user/tasks/create-realm.yml
  roles/rhsso-user/templates/evals-user-realm.j2
Labels: approved, lgtm, size/L

#1135 feat(INTLY-4102): add new solution pattern cohesion templates
  roles/walkthroughs/defaults/main.yml
  roles/walkthroughs/tasks/camel_orders_api.yml
  roles/walkthroughs/tasks/nodejs_orders_management_ui.yml
  roles/walkthroughs/tasks/walkthroughs.yml
  roles/walkthroughs/templates/camel_orders_api.yml
  roles/walkthroughs/templates/crud_spboot_example.yml
  roles/walkthroughs/templates/messaging_work_queue_nodejs.yml
  roles/walkthroughs/templates/nodejs_orders_management_ui.yml
Labels: approved, lgtm, size/L

#1195 Update webapp to 2.20.3
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1196 Update manifest.yaml
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1197 fixed ups server status check when installing backups
  roles/ups/tasks/backup.yml
Labels: approved, lgtm, size/XS

#1202 Add Makefile with basic test targets
  .ansible-lint
  Makefile
  openshift-ci/Dockerfile.tools
  openshift-ci/OWNERS
  openshift-ci/README.md
  openshift-ci/test/run
  test/format.sh
  test/install.sh
  test/upgrade.sh
Labels: approved, lgtm, size/L

#1198 fix: handle walkthrough upgrade/install and restore old work queue/spring templates
  playbooks/upgrades/upgrade.yaml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/walkthroughs/tasks/camel_orders_api.yml
  roles/walkthroughs/tasks/crud_spboot_example.yml
  roles/walkthroughs/tasks/location_soap.yml
  roles/walkthroughs/tasks/messaging_work_queue_nodejs.yml
  roles/walkthroughs/tasks/nodejs_order_entry_ui.yml
  roles/walkthroughs/tasks/nodejs_orders_management_ui.yml
  roles/walkthroughs/tasks/uninstall.yml
  roles/walkthroughs/tasks/upgrade.yml
  roles/walkthroughs/tasks/walkthroughs.yml
  roles/walkthroughs/templates/crud_spboot_example.yml
  roles/walkthroughs/templates/messaging_work_queue_nodejs.yml
  roles/walkthroughs/templates/nodejs_order_entry_ui.yml
  roles/walkthroughs/templates/nodejs_orders_management_ui.yml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/XL

#1203 make sure syndesis-operator CLI is running with the right context file
  inventories/group_vars/all/common.yml
  inventories/group_vars/osd/osd.yml
  inventories/group_vars/poc/poc.yml
  roles/fuse_managed/tasks/check_readiness.yml
  roles/fuse_managed/tasks/main.yml
Labels: approved, lgtm, size/M

#1201 ups update for INTLY-4511
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, product update, size/XS, ups

#1204 Cherrypick 1198
  playbooks/upgrades/upgrade.yaml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/walkthroughs/tasks/camel_orders_api.yml
  roles/walkthroughs/tasks/crud_spboot_example.yml
  roles/walkthroughs/tasks/location_soap.yml
  roles/walkthroughs/tasks/messaging_work_queue_nodejs.yml
  roles/walkthroughs/tasks/nodejs_order_entry_ui.yml
  roles/walkthroughs/tasks/nodejs_orders_management_ui.yml
  roles/walkthroughs/tasks/uninstall.yml
  roles/walkthroughs/tasks/upgrade.yml
  roles/walkthroughs/tasks/walkthroughs.yml
  roles/walkthroughs/templates/crud_spboot_example.yml
  roles/walkthroughs/templates/messaging_work_queue_nodejs.yml
  roles/walkthroughs/templates/nodejs_order_entry_ui.yml
  roles/walkthroughs/templates/nodejs_orders_management_ui.yml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/XL

#1209 Bump web-app to 2.20.7 and operator release tag to v0.0.39
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1210 Update solution explorer to 2.20.8 and operator to v0.0.40
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1208 INTLY-4541 Use count for sequence
  roles/rhsso-user/tasks/create-eval-user-realms.yml
Labels: approved, lgtm, size/XS

#1219 bumped webapp operator version to 0.0.41
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS
