Repository integr8ly/installation, pull requests merged in 2020-01, with the labels that each got.

#1207 Upgrade fuse
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/fuse/tasks/_upgrade_fuse_online_imagestreams.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/templates/syndesis-customresource.yml.j2
Labels: approved, lgtm, size/L

#1225 upgrade fuse
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrades/upgrade.yaml
  roles/fuse/tasks/_upgrade_fuse_online_imagestreams.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/templates/syndesis-customresource.yml.j2
Labels: approved, lgtm, size/L

#1226 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1227 bump version of the WTs
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/XS

#1212 update mobile wt version
  inventories/group_vars/all/manifest.yaml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/XS

#1229 make sure the upgrade playbook can run against 1.6.0 release
  playbooks/upgrades/upgrade.yaml
Labels: approved, lgtm, size/XS

#1231 ignore errors if no fuse deployment is triggered
  roles/fuse_managed/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#1235 chore: bump datasync_template_tag
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1236 Updating predictive PVC checks to check that PVC still exists
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm, size/XS

#1233 wait longer for the fuse imagestreams to be ready
  roles/fuse_managed/tasks/upgrade.yml
Labels: approved, lgtm, size/XS

#1234 create one shared realm for the walkthroughs
  inventories/group_vars/all/manifest.yaml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/S

#1240 Intly 4660 user sso realm cp cherry-pick
  inventories/group_vars/all/manifest.yaml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, size/S

#1242 Add support for specifying any number of additional seed users to be created/configured during install
  playbooks/install_user_rhsso.yml
  roles/3scale/tasks/users.yml
  roles/fuse_managed/tasks/main.yml
  roles/gitea/tasks/main.yml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/rhsso-user/tasks/create-realm.yml
  roles/rhsso-user/templates/master-realm.json.j2
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/_inject_user.yml
  roles/rhsso/tasks/apply_ocp_roles.yaml
  roles/rhsso/tasks/expand_user_list.yml
  roles/rhsso/tasks/main.yml
  roles/rhsso/templates/keycloak-realm.json.j2
  roles/rhsso/templates/normalize_seed_users.yaml.j2
Labels: approved, lgtm, size/L

#1243 bump gitea operator version
  inventories/group_vars/all/manifest.yaml
  roles/gitea/tasks/main.yml
Labels: lgtm, size/S

#1246 Upgrade playbook updates v1.6
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrades/upgrade.yaml
  playbooks/upgrades/upgrade.yml
Labels: approved, lgtm, size/L

#1248 [WIP] 3scale update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: 3Scale, approved, do-not-merge/work-in-progress, lgtm, product update, size/XS

#1224 [WIP] 3scale update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: 3Scale, approved, do-not-merge/work-in-progress, lgtm, product update, size/XS

#1247 Replace playbooks/upgrades/upgrade.yml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrades/upgrade.yaml
Labels: approved, lgtm, size/L

#1255 Import new upgrade playbook (playbooks/upgrade.yml) from the old one …
  playbooks/upgrades/upgrade.yaml
  playbooks/upgrades/upgrade.yml
Labels: approved, lgtm, size/XS

#1244 INTLY-3957 - prevent linking customer-admin to incorrect account on user-sso
  playbooks/install_user_rhsso.yml
  playbooks/upgrade.yml
  roles/rhsso-user/tasks/create-eval-user-realms.yml
  roles/rhsso-user/tasks/disable-idp-review-link-confirm.yml
  roles/rhsso-user/tasks/obtain-user-sso-token.yml
  scripts/upgrade.template.yml
Labels: approved, lgtm, size/L

#1249 amq-online update 1.3.2
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: amq-online, approved, lgtm, product update, size/XS

#1257 User sso upgrade images
  playbooks/upgrade.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso-user/tasks/upgrade_images.yml
  scripts/upgrade.template.yml
Labels: approved, lgtm, size/S

#1258 User sso upgrade images (v1.6)
  playbooks/upgrade.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso-user/tasks/upgrade_images.yml
  scripts/upgrade.template.yml
Labels: approved, lgtm, size/S

#1250 rhsso update 1.9.5
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: approved, lgtm, product update, rhsso, size/XS

#1262 Update rhsso operator release tag to v1.9.5
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1261 Updated amq-online product version to 1.3.2
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS
