Repository integr8ly/installation, pull requests merged in 2020-05, with the labels that each got.

#1337 request approval permission for user JameelB
  OWNERS
Labels: approved, lgtm

#1332 V1.7 add missing rc2 changes
  inventories/group_vars/all/manifest.yaml
  roles/apicurito/tasks/main.yml
  roles/fuse_managed/tasks/main.yml
  roles/middleware_monitoring_config/defaults/main.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm

#1331 INTLY-6413-cp
  roles/middleware_monitoring/defaults/main.yml
  roles/middleware_monitoring/tasks/uninstall.yml
Labels: approved, lgtm

#1335 use new walkthrough release 1.12.1
  inventories/group_vars/all/manifest.yaml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1342 INTLY-7080: Ensure fuse binary is removed during uninstall
  roles/fuse_managed/tasks/uninstall.yml
Labels: approved, lgtm

#1346 ensure fuse binary is removed during uninstall
  roles/fuse_managed/tasks/uninstall.yml
Labels: approved, lgtm

#1345 update version from 1.6.0 to 1.7.0 in manifest file (Cherrypick)
  roles/launcher/defaults/main.yml
Labels: approved, lgtm

#1338 INTLY-7166
  playbooks/group_vars/all/upgrade.yml
  roles/backup/tasks/upgrade_images.yml
Labels: approved, lgtm

#1333 Intly 7196
  playbooks/upgrade.yml
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
  roles/enmasse/tasks/upgrade_images.yml
Labels: approved, lgtm

#1336 INTLY-7393: Fix failing upgrade due to failed fuse image import
  playbooks/upgrade.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/tasks/upgrade_images.yml
Labels: approved, lgtm

#1339 Cherry Pick for INTLY-7166
  roles/backup/tasks/upgrade_images.yml
Labels: approved, lgtm

#1340 Intly 7196 cherry pick master
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
  roles/enmasse/tasks/upgrade_images.yml
Labels: approved, lgtm

#1343 INTLY-7393: Fix failing upgrade due to failed fuse image import
  playbooks/upgrade.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/tasks/upgrade_images.yml
Labels: approved, lgtm

#1347 use new walkthrough release 1.12.1
  inventories/group_vars/all/manifest.yaml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1341 INTLY-7382 Update 'launcher_catalog_git_ref' from 1.6.0 to 1.7.0 in manifest file
  roles/launcher/defaults/main.yml
Labels: approved, lgtm

#1349 INTLY-7206: Ensure apicurito version upgrades from 1.5 to 1.6
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/apicurito/defaults/main.yml
  roles/apicurito/tasks/upgrade.yml
  roles/apicurito/tasks/upgrade_images.yml
  roles/backup/tasks/upgrade_images.yml
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
Labels: approved, lgtm

#1350 INTLY-7206: Add apicurito upgrade playbook
  playbooks/group_vars/all/upgrade.yml
  roles/apicurito/defaults/main.yml
  roles/apicurito/tasks/upgrade.yml
  roles/apicurito/tasks/upgrade_images.yml
  roles/backup/tasks/upgrade_images.yml
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
Labels: approved, lgtm

#1354 update walkthrough location to include 1b
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1355 update walkthrough location to include 1b
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1356 INTLY-7482 - upgrade - update launcher config map
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
Labels: approved, lgtm

#1357 INTLY-7479
  playbooks/upgrade.yml
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
  roles/enmasse/tasks/upgrade_prometheus_rule.yml
Labels: approved, lgtm

#1360 Adding a new role for recreating prometheus rules after enmasse upgrade
  roles/enmasse/tasks/upgrade_1.6_1.7.yml
  roles/enmasse/tasks/upgrade_prometheus_rule.yml
Labels: approved, lgtm

#1358 INTLY-7486: ensure amq console link in solution explorer points to the parent amq console link
  inventories/group_vars/all/manifest.yaml
  roles/customisation/tasks/main.yaml
  roles/customisation/templates/inventory.j2
  roles/customise-web-console/defaults/main.yml
  roles/customise-web-console/tasks/install.yml
  roles/customise-web-console/tasks/upgrade.yml
  roles/enmasse/tasks/upgrade_prometheus_rule.yml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
  roles/webapp/templates/cr.yaml.j2
Labels: approved, lgtm

#1359 INTLY-7486 (1.7): ensure amq console link in solution explorer points to the parent amq console link
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrade.yml
  roles/customisation/tasks/main.yaml
  roles/customisation/templates/inventory.j2
  roles/customise-web-console/defaults/main.yml
  roles/customise-web-console/tasks/install.yml
  roles/customise-web-console/tasks/upgrade.yml
  roles/enmasse/tasks/upgrade_prometheus_rule.yml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/provision-webapp.yml
  roles/webapp/tasks/upgrade.yaml
  roles/webapp/templates/cr.yaml.j2
Labels: approved, lgtm

#1361 Adding automation for resetting the upgrade files on master after final release is cut
  docs/release.md
  scripts/release.sh
  scripts/upgrade.template.yml
Labels: approved, lgtm

#1363 Reset upgrade variables after final release release-1.7.0
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
Labels: approved, lgtm

#1351 INTLY-6512
  CHANGELOG.md
  README.adoc
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrade.yml
  roles/3scale/tasks/heimdall.yml
  roles/apicurito/tasks/heimdall.yml
  roles/codeready/tasks/heimdall.yml
  roles/enmasse/tasks/heimdall.yml
  roles/fuse_managed/tasks/heimdall.yml
  roles/heimdall/tasks/main.yml
  roles/heimdall/templates/heimdall-dockercfg.yml.j2
Labels: approved, lgtm

#1287 Filtering which https-metrics with federate from cluster prom
  roles/middleware_monitoring_config/templates/jobs/openshift_monitoring_federation.j2
Labels: approved, lgtm

#1362 Increased webapp wait for pod retries
  roles/webapp/tasks/provision-webapp.yml
Labels: approved, lgtm

#1365 add missing che_version var
  roles/codeready/tasks/install.yml
Labels: approved, lgtm

#1299 fuse-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/fuse_managed/tasks/wait_for_rollouts.yml
Labels: approved, fuse-online, lgtm, product update

#1291 3scale update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: 3Scale, approved, lgtm, product update
