Repository integr8ly/installation, pull requests merged in 2020-02, with the labels that each got.

#1259 Fix fuse install now that fuse uses floating tags
  inventories/group_vars/all/manifest.yaml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/upgrade_images.yml
Labels: approved, lgtm, size/M

#1253 CSSRE-479: Show pod name and update annotations
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1264 Setting eval_self_signed_certs in pds group vars
  inventories/group_vars/pds/pds.yml
Labels: approved, lgtm, size/XS

#1263 Update changelog
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1267 Changing codeready postgresql image tag from latest to 1-52
  roles/codeready/defaults/main.yml
Labels: approved, lgtm, size/XS

#1270 bumping backup version
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1273 install codeready using the cli tool
  roles/codeready/defaults/main.yml
  roles/codeready/tasks/download_installer.yml
  roles/codeready/tasks/install.yml
  roles/codeready/tasks/main.yaml
  roles/codeready/tasks/uninstall.yml
  roles/codeready/templates/che-cluster-cr.yaml.j2
  roles/codeready/templates/config.yaml
Labels: approved, lgtm, size/L

#1271 Allow dedicated-admins group to modify amq online configs
  playbooks/upgrade.yml
  roles/enmasse/defaults/main.yml
  roles/enmasse/tasks/install.yml
  roles/enmasse/tasks/service_admin.yml
  roles/enmasse/templates/service_admin_role_binding.yml.j2
Labels: approved, lgtm, size/M
