Repository integr8ly/installation, pull requests merged in 2020-08, with the labels that each got.

#1393 Updating webapp walkthrough locations
  playbooks/upgrade.yml
  roles/webapp/defaults/main.yml
  roles/webapp/tasks/upgrade.yaml
  roles/webapp/tasks/upgrade_rhmi_1.7_to_1.8.yaml
Labels: approved, lgtm

#1396 update ups-operator version
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1397 INLTY-9733 - Revert Heimdall installation
  CHANGELOG.md
  README.adoc
  inventories/group_vars/all/manifest.yaml
  roles/3scale/tasks/heimdall.yml
  roles/apicurito/tasks/heimdall.yml
  roles/codeready/tasks/heimdall.yml
  roles/enmasse/tasks/heimdall.yml
  roles/fuse_managed/tasks/heimdall.yml
  roles/heimdall/tasks/main.yml
Labels: approved, lgtm

#1399 apply templates to avoid duplication
  roles/walkthroughs/tasks/camel_orders_api.yml
  roles/walkthroughs/tasks/crud_spboot_example.yml
  roles/walkthroughs/tasks/location_soap.yml
  roles/walkthroughs/tasks/messaging_work_queue_nodejs.yml
  roles/walkthroughs/tasks/nodejs_order_entry_ui.yml
  roles/walkthroughs/tasks/nodejs_orders_management_ui.yml
  roles/walkthroughs/tasks/walkthroughs.yml
Labels: approved, lgtm

#1402 Intly 9784
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrade.yml
Labels: approved, lgtm

#1403 3scale update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/3scale/tasks/upgrade_2.8_to_2.9.yaml
  roles/webapp/defaults/main.yml
Labels: 3Scale, product update

#1408 update walkthroughs
  roles/webapp/defaults/main.yml
Labels: lgtm
