Repository integr8ly/installation, pull requests merged in 2020-03, with the labels that each got.

#1275 Disable gitea by default
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm, size/XS

#1274 Updated alert manager email template
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/tasks/create_alertmanager.yml
  roles/middleware_monitoring_config/tasks/upgrade_alert_manager_email.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
  roles/middleware_monitoring_config/templates/custom-alert-manager-email.tmpl.j2
Labels: approved, lgtm, size/L

#1277 Override the default memory values for JVM for codeready workspaces
  roles/codeready/templates/che-cluster-cr.yaml.j2
Labels: approved, lgtm, size/S

#1276 improve resiliency of ssos
  CHANGELOG.md
  playbooks/install.yml
  playbooks/upgrade.yml
  roles/3scale/defaults/main.yml
  roles/3scale/tasks/install.yml
  roles/3scale/tasks/new_limits.yml
  roles/3scale/tasks/resources.yml
  roles/3scale/templates/resource-limits.yml.j2
  roles/enmasse/defaults/main.yml
  roles/resource_limits/defaults/main.yml
  roles/resource_limits/tasks/main.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso/defaults/main.yml
Labels: approved, lgtm, size/L

#1279 bumps backup container image version
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1281 update ups operator image
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/cve.yml
  playbooks/group_vars/all/upgrade.yml
  roles/ups/tasks/upgrade_images.yml
Labels: approved

#1280 update ups operator image
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/cve.yml
  playbooks/group_vars/all/upgrade.yml
  roles/ups/tasks/upgrade_images.yml
Labels: approved, lgtm

#1288 fix version shown in webapp about
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrade.yml
  roles/webapp/tasks/update_version_info.yml
Labels: approved

#1282 Use kube_job_failed metric to check for job completion spec
  roles/backup/templates/backup-monitoring-alerts.yml.j2
Labels: approved, lgtm, needs-ok-to-test

#1289 INTLY-2544 - allow customer-admins view 3Scale logs in Kibana
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/3scale/tasks/admins-view-namespace.yml
  roles/3scale/tasks/install.yml
  roles/3scale/templates/get-namespaces-role.yml.j2
  roles/3scale/templates/get-namespaces-rolebinding.yml.j2
Labels: approved, lgtm

#1294 updated alert trigger and severity
  roles/backup/templates/backup-monitoring-alerts.yml.j2
Labels: approved, lgtm

#1296 add enmasse postgres image var
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: approved, lgtm
