Repository integr8ly/installation, pull requests merged in 2020-04, with the labels that each got.

#1295 Fix sso podcount alert
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/tasks/upgrade.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm

#1285 fuse-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
Labels: approved, fuse-online, lgtm, product update

#1298 apply refined cpu/mem requests values for sso's/amq/3scale
  roles/3scale/defaults/main.yml
  roles/enmasse/defaults/main.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso/defaults/main.yml
Labels: approved, lgtm

#1300 add rhsso and rhssouser to the upgrades list for upgrades from 1.6.1
  playbooks/group_vars/all/upgrade.yml
Labels: approved, lgtm

#1301 Intly 6500 update 3scale
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/cve.yml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/3scale/tasks/upgrade_2.7_to_2.8.yml
  roles/3scale/tasks/upgrade_images.yml
  roles/3scale/tasks/wait_for_rollouts.yml
  roles/webapp/tasks/update_version_info.yml
Labels: approved, lgtm

#1303 Intly 6396 Update fuse
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
  roles/fuse/tasks/upgrade.yml
  roles/fuse_managed/defaults/main.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/templates/syndesis-customresource.yml.j2
  roles/msbroker/files/upgrade-cluster-role.json
Labels: approved, lgtm

#1304 auto-dismiss interactive prompts by default
  roles/resource_limits/defaults/main.yml
  roles/resource_limits/tasks/main.yml
  roles/resource_limits/tasks/patch_resource.yml
Labels: approved, lgtm

#1306 INTLY-6835 Force download of fuse binary
  roles/fuse_managed/tasks/main.yml
Labels: approved, lgtm

#1297 CSSRE-518: Added variables and config for alertmanager slack integration
  roles/middleware_monitoring_config/defaults/main.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm, needs-ok-to-test

#1309 INTLY-6525: Update heimdall version to release-1.0.1
  CHANGELOG.md
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1314 fixes to unblock QE
  inventories/group_vars/osd/osd.yml
  roles/enmasse/defaults/main.yml
  roles/fuse_managed/tasks/upgrade.yml
  roles/fuse_managed/tasks/wait_for_rollouts.yml
Labels: approved, lgtm

#1315 fix: update amq-service-broker oauth endpoint in blackbox target
  roles/middleware_monitoring_config/templates/blackboxtargets.yml.j2
Labels: approved, lgtm

#1311 update webapp to 2.22.3 (operator version 0.0.49)
  inventories/group_vars/all/manifest.yaml
Labels: lgtm

#1313 Resetting the upgrade playbook on master
  docs/release.md
  playbooks/upgrade.yml
Labels: approved, lgtm

#1321 remove deploy/api-server resource override
  roles/enmasse/defaults/main.yml
Labels: approved, lgtm

#1312 INTLY-4649 Allow traffic from middleware namespaces
  playbooks/install.yml
  roles/openshift/files/allow-from-middleware-namespaces.json
  roles/openshift/tasks/add_network_policy.yml
Labels: approved, lgtm

#1316 update sso version in manifest
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1317 Intly-6419 - Update fail message for 2nd run of upgrade
  roles/prerequisites/tasks/upgrade.yml
Labels: approved, lgtm

#1325 resetting upgrade vars on master, updating version 1.7.0
  playbooks/group_vars/all/upgrade.yml
Labels: approved, lgtm

#1322 Update enmasse version to 1.4.1.GA
  inventories/group_vars/all/manifest.yaml
  roles/enmasse/templates/enmasse_hosts.j2
Labels: approved, lgtm

#1323 wait for apicurito pods to be ready
  roles/apicurito/tasks/main.yml
Labels: approved, lgtm

#1324 INTLY-6419 Cherrypick
  roles/prerequisites/tasks/upgrade.yml
Labels: approved, lgtm

#1320 V1.7 rc2 changes
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  playbooks/install.yml
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/templates/blackboxtargets.yml.j2
  roles/openshift/files/allow-from-middleware-namespaces.json
  roles/openshift/tasks/add_network_policy.yml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1326 updates for solution explorer 2.22.6
  inventories/group_vars/all/manifest.yaml
  roles/webapp/defaults/main.yml
Labels: approved, lgtm

#1327 Bump Fuse templates version - apicurito-ui apicurito-generator image streams
  inventories/group_vars/all/manifest.yaml
  roles/fuse/tasks/main.yml
  roles/fuse/tasks/upgrade.yml
  roles/fuse/tasks/upgrade_images.yml
Labels: approved, lgtm

#1329 Intly 7192 bump fuse template version v1.7 cherrypick
  inventories/group_vars/all/manifest.yaml
  roles/fuse/tasks/main.yml
  roles/fuse/tasks/upgrade.yml
  roles/fuse/tasks/upgrade_images.yml
Labels: approved, lgtm

#1330 INTLY-6950: Update enmasse version to 1.4.1.GA
  inventories/group_vars/all/manifest.yaml
  roles/enmasse/templates/enmasse_hosts.j2
Labels: approved, lgtm

#1334 add jameelb to approvers
  OWNERS
Labels: approved, lgtm
