Repository integr8ly/installation, pull requests merged in 2020-07, with the labels that each got.

#1377 cherry pick to v1.7 adding dummy/null reciever for UnifiedPushJavaHeapThresholdExceeded alert
  CHANGELOG.md
  roles/middleware_monitoring_config/tasks/create_alertmanager.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm

#1376 INTLY: 8401: amq 1.4.4 cherrypick to v1.7 branch
  CHANGELOG.md
  inventories/group_vars/all/manifest.yaml
  roles/enmasse/tasks/upgrade_images.yml
Labels: approved, lgtm

#1378 remove unused templates from ups
  CHANGELOG.md
  roles/ups/defaults/main.yml
  roles/ups/templates/grafana_dashboard.yml.j2
  roles/ups/templates/operator_grafana_dashboard.yml.j2
  roles/ups/templates/operator_prometheus_rule.yml.j2
  roles/ups/templates/prometheus_rule.yml.j2
Labels: approved, lgtm

#1380 add patch to create missing amq namespaces
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/enmasse/tasks/patch_namespaces_upgrade_1.6_1.7.yml
Labels: approved, lgtm

#1379 INTLY-9063 cherrypick NodeCPUUtilitisation alerts
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm

#1381 Intly 9093 9097 manifest versions mismatch
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1383 Reset upgrade variables after final release release-1.7.1
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
Labels: approved, lgtm

#1384 fix: Update DataSync walkthough
  roles/webapp/defaults/main.yml
Labels: approved, lgtm, ok-to-test

#1382 update ssopodcount alert to check for at least 4 pods to allow for scaling
  CHANGELOG.md
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved

#1388 Update OWNERS
  OWNERS
Labels: approved, lgtm

#1387 Update PV usage alerts to match upstream kubernetes-mixin
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm

#1386 amq-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  roles/enmasse/tasks/_download_enmasse_artifact.yml
  roles/enmasse/tasks/_install_enmasse_from_artifact.yml
Labels: amq-online, approved, lgtm, product update

#1392 Intly 9312
  inventories/group_vars/all/manifest.yaml
  playbooks/upgrade.yml
  roles/rhsso-user/defaults/main.yml
  roles/rhsso-user/tasks/upgrade_images.yml
  roles/rhsso/defaults/main.yml
  roles/rhsso/tasks/upgrade_images.yml
  roles/walkthroughs/defaults/main.yml
Labels: approved, lgtm

#1394 fix typo
  inventories/group_vars/all/manifest.yaml
Labels: approved, lgtm

#1391 fix monitoring template
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm
