Repository integr8ly/installation, pull requests merged in 2020-06, with the labels that each got.

#1366 INTLY-7813 Add new alerts for high node cpu & memory utilisation
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_alerts.yml.j2
Labels: approved, lgtm

#1368 INTLY-8400: Removed JobRunningTimeExceeded (>300) and include in upgrades
  docs/monitoring_docs.asciidoc
  playbooks/upgrade.yml
  roles/backup/templates/backup-monitoring-alerts.yml.j2
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm, ok-to-test

#1369 Add custom SOP URLs to enmasse alert mails; Fix alertmanager slack vars
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/defaults/main.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
  roles/middleware_monitoring_config/templates/custom-alert-manager-email.tmpl.j2
Labels: approved, lgtm

#1370 INTLY-8459 Allow for metric returning a 0 value
  CHANGELOG.md
  playbooks/upgrade.yml
  roles/middleware_monitoring_config/templates/kube_state_metrics_3scale_alerts.yml.j2
Labels: approved, lgtm

#1373 INTLY-8400: cherry-pick to v1.7 branch
  docs/monitoring_docs.asciidoc
  playbooks/upgrade.yml
  roles/backup/templates/backup-monitoring-alerts.yml.j2
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm

#1364 amq-online update
  inventories/group_vars/all/manifest.yaml
  playbooks/group_vars/all/upgrade.yml
  roles/enmasse/tasks/upgrade_images.yml
Labels: amq-online, approved, lgtm, product update

#1374 Revert "Reset upgrade variables after final release release-1.7.0"
  playbooks/group_vars/all/upgrade.yml
  playbooks/upgrade.yml
Labels: approved, lgtm

#1372 intly-8601 add dummy/null receiver for UnifiedPushJavaHeapThresholdExceeded alert
  CHANGELOG.md
  roles/middleware_monitoring_config/tasks/create_alertmanager.yml
  roles/middleware_monitoring_config/templates/alertmanager.yml.j2
Labels: approved, lgtm

#1375 Intly 8459 probe success alerts fix cherry pick
  CHANGELOG.md
  roles/middleware_monitoring_config/templates/kube_state_metrics_3scale_alerts.yml.j2
Labels: approved, lgtm
